name: Mobile Development Build & Deploy

on:
  push:
    branches: [ "development" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.4'
          channel: 'stable'
          cache: false

      - name: Get Dependencies
        run: flutter pub get
        working-directory: ./

      - name: Generate Code (Build Runner)
        run: |
          flutter pub run build_runner clean
          flutter pub run build_runner build --delete-conflicting-outputs
        working-directory: ./

      - name: Build Debug APK
        run: flutter build apk --debug --dart-define=API_URL=${{ secrets.DEV_API_URL }}
        working-directory: ./

      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_ANDROID_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_CLI_CREDENTIALS }}
          groups: testers
          file: build/app/outputs/flutter-apk/app-debug.apk
